import i18n, { Translations } from "./i18n";
import Button from "./Components/Button";
import AbstractModal from "./Components/Modal/AbstractModal";
import ConfirmAlertModal from "./Components/Modal/ConfirmAlertModal";
import RobotLogModal from "./Components/Modal/RobotLogModal";
import Drawer from "./Components/Drawer";
import Collapse from "./Components/Collapse";
import VerticalBar from "./Components/VerticalBar/VerticalBar";
import ContextMenu from "./Components/ContextMenu";
import Table from "./Components/Table";
import Tabs from "./Components/Tabs";
import Text from "./Components/Text";
import Toggle from "./Components/Toggle";
import SearchInput from "./Components/SearchInput";
import Breadcrumb from "./Components/Breadcrumb";
import Select from "./Components/Select";
import { snackbar } from "./Components/Snackbar/Snackbar";
import Themes from "./styles/Themes";
import Logs from "./Components/Logs/Logs";
import LoginForm from "./Components/LoginForm/LoginForm";
import NotAuthorized from "./Components/LoginForm/LoginPanel";
import ProfileMenu from "./Components/ProfileMenu/ProfileMenu";
import ResetPasswordModal from "./Components/ProfileMenu/ResetPassword";
import TimeFilters from "./Components/Logs/LogsFilterBar/sub-components/TimeFilters";
import FilterIcon from "./Components/Logs/LogsFilterBar/sub-components/_shared/FiltersIcon/FiltersIcon";
import SelectScopeModal, { getAllData } from "./Components/Modal/SelectScopeModal";
import HTMLPopper from "./Components/Popper/HTMLPopper";
import HomeMenuPopper from "./Components/HomeMenu/HomeMenu";
import HomeMenuSkeleton from "./Components/HomeMenu/HomeMenuSkeleton";
import ErrorBoundary from "./Components/ErrorBoundary";
// import HOCs
import withOfflineValidation from "./Components/HOCs/withOfflineValidation";
import withAuthentication, { authSub } from "./Components/HOCs/withAuthentication";
import withNotification from "./Components/HOCs/withNotification";
import withTheme, { themeSub } from "./Components/HOCs/withTheme";
import withDefaults from "./Components/HOCs/withDefaults";
import withError from "./Components/HOCs/withError";
// import Translations
import ExportPdf from "./exporters/pdf";
import ExportCsv from "./exporters/csv";
export {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  AppBar,
  Autocomplete,
  Avatar,
  Backdrop,
  Badge,
  Box,
  Button as BaseButton,
  ButtonBase,
  Card,
  CardActions,
  CardContent,
  CardHeader,
  Checkbox,
  Chip,
  CircularProgress,
  ClickAwayListener,
  Collapse as BaseCollapse,
  CssBaseline,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Drawer as BaseDrawer,
  Fab,
  Fade,
  FormControl,
  FormControlLabel,
  FormHelperText,
  Grid,
  IconButton,
  Input,
  InputAdornment,
  InputBase,
  InputLabel,
  LinearProgress,
  Link,
  List,
  ListItem,
  ListItemAvatar,
  ListItemIcon,
  ListItemSecondaryAction,
  ListItemText,
  Menu,
  MenuItem,
  Modal,
  NativeSelect,
  OutlinedInput,
  Paper,
  // ParameterLine,
  Popper,
  Radio,
  RadioGroup,
  Select as BaseSelect,
  Skeleton,
  SnackbarContent,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  SvgIcon,
  Switch,
  Table as BaseTable,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  ToggleButton,
  ToggleButtonGroup,
  Toolbar,
  Tooltip,
  Typography,
  styled,
} from "@mui/material";
export {
  amber,
  green,
  grey,
} from "@mui/material/colors";
export {
  alpha,
} from "@mui/material/styles";
export {
  AcUnit as AcUnitIcon,
  AccessAlarm as AccessAlarmIcon,
  Accessibility as AccessibilityIcon,
  AccountBalance as AccountBalanceIcon,
  AccountTree as AccountTreeIcon,
  Adb as AdbIcon,
  Add as AddIcon,
  AddBox as AddBoxIcon,
  AddIcCall as AddIcCallIcon,
  AirplanemodeActive as AirplanemodeActiveIcon,
  Apps as AppsIcon,
  ArrowBackRounded as ArrowBackRoundedIcon,
  ArrowDownward as ArrowDownwardIcon,
  ArrowDropDown as ArrowDropDownIcon,
  ArrowForwardRounded as ArrowForwardRoundedIcon,
  ArrowRight as ArrowRightIcon,
  ArrowRightAlt as ArrowRightAltIcon,
  ArrowUpward as ArrowUpwardIcon,
  Assignment as AssignmentIcon,
  AssignmentInd as AssignmentIndIcon,
  Autorenew as AutorenewIcon,
  Battery20 as Battery20Icon,
  Battery30 as Battery30Icon,
  Battery50 as Battery50Icon,
  Battery60 as Battery60Icon,
  Battery80 as Battery80Icon,
  Battery90 as Battery90Icon,
  BatteryAlert as BatteryAlertIcon,
  BatteryFull as BatteryFullIcon,
  BlockRounded as BlockRoundedIcon,
  Bookmark as BookmarkIcon,
  BugReport as BugReportIcon,
  Build as BuildIcon,
  CallMade as CallMadeIcon,
  Cancel as CancelIcon,
  Check as CheckIcon,
  CheckCircle as CheckCircleIcon,
  CheckBox as CheckBoxIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChromeReaderMode as ChromeReaderModeIcon,
  Clear as ClearIcon,
  Close as CloseIcon,
  CloudDownload as CloudDownloadIcon,
  Code as CodeIcon,
  Comment as CommentIcon,
  Compare as CompareIcon,
  CompareArrows as CompareArrowsIcon,
  Dashboard as DashboardIcon,
  Delete as DeleteIcon,
  DeleteOutline as DeleteOutlineIcon,
  Description as DescriptionIcon,
  DeviceHub as DeviceHubIcon,
  Download as DownloadIcon,
  DragIndicator as DragIndicatorIcon,
  Edit as EditIcon,
  Email as EmailIcon,
  Error as ErrorIcon,
  ExitToAppOutlined as ExitToAppOutlinedIcon,
  ExpandLess as ExpandLessIcon,
  ExpandMore as ExpandMoreIcon,
  Favorite as FavoriteIcon,
  FiberManualRecord as FiberManualRecordIcon,
  FileCopy as FileCopyIcon,
  FileCopyOutlined as FileCopyOutlinedIcon,
  FilterList as FilterListIcon,
  FirstPage as FirstPageIcon,
  FolderOpen as FolderOpenIcon,
  GetApp as GetAppIcon,
  Grade as GradeIcon,
  Grain as GrainIcon,
  HelpOutlineOutlined as HelpOutlineOutlinedIcon,
  Home as HomeIcon,
  Image as ImageIcon,
  Info as InfoIcon,
  Input as InputIcon,
  Keyboard as KeyboardIcon,
  KeyboardArrowDown as KeyboardArrowDownIcon,
  KeyboardArrowUp as KeyboardArrowUpIcon,
  LastPage as LastPageIcon,
  LibraryBooks as LibraryBooksIcon,
  Link as LinkIcon,
  ListAlt as ListAltIcon,
  Lock as LockIcon,
  LockOpen as LockOpenIcon,
  LowPriority as LowPriorityIcon,
  Money as MoneyIcon,
  MoreHoriz as MoreHorizIcon,
  MoreVert as MoreVertIcon,
  MyLocationOutlined as MyLocationOutlinedIcon,
  NoteAdd as NoteAddIcon,
  NotificationsActive as NotificationsActiveIcon,
  OpenInNew as OpenInNewIcon,
  PauseCircleOutline as PauseCircleOutlineIcon,
  People as PeopleIcon,
  PermDataSettingOutlined as PermDataSettingOutlinedIcon,
  PermMedia as PermMediaIcon,
  PieChart as PieChartIcon,
  PlayArrow as PlayArrowIcon,
  PlayArrowOutlined as PlayArrowOutlinedIcon,
  PlayCircleOutline as PlayCircleOutlineIcon,
  Remove as RemoveIcon,
  SaveAlt as SaveAltIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Stop as StopIcon,
  Storage as StorageIcon,
  Subject as SubjectIcon,
  SupervisedUserCircle as SupervisedUserCircleIcon,
  SwapHoriz as SwapHorizIcon,
  Timer as TimerIcon,
  TimerOff as TimerOffIcon,
  ToggleOn as ToggleOnIcon,
  Tune as TuneIcon,
  Undo as UndoIcon,
  ViewColumn as ViewColumnIcon,
  ViewInAr as ViewInArIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Warning as WarningIcon,
  Web as WebIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
} from "@mui/icons-material";
export {
  makeStyles,
  withStyles,
  withTheme as withBaseTheme,
  useTheme,
  ThemeProvider,
} from "@mui/styles";
export {
  TreeView,
  TreeItem,
} from "@mui/x-tree-view";
export {
  default as MaterialTable,
  MTableAction,
  MTableCell,
  MTableEditRow,
  MTableHeader,
  MTableToolbar,
} from "@material-table/core";
export { DropzoneArea } from "react-mui-dropzone";

export {
  withOfflineValidation,
  withAuthentication,
  withNotification,
  withTheme,
  authSub,
  themeSub,
  withDefaults,
  withError,
  Button,
  AbstractModal,
  ConfirmAlertModal,
  SelectScopeModal,
  getAllData,
  RobotLogModal,
  Drawer,
  Collapse,
  VerticalBar,
  ContextMenu,
  Table,
  Tabs,
  Text,
  Themes,
  Toggle,
  SearchInput,
  Breadcrumb,
  Select,
  snackbar,
  Logs,
  TimeFilters,
  FilterIcon,
  LoginForm,
  ProfileMenu,
  ResetPasswordModal,
  HTMLPopper,
  HomeMenuPopper,
  HomeMenuSkeleton,
  ErrorBoundary,
  Translations,
  i18n,
  NotAuthorized,
  ExportPdf,
  ExportCsv,
};
